// <auto-generated/>
// Generated internal POCO types for EventBridge from AWS service model
#nullable enable

namespace LocalSqsSnsMessaging.EventBridge.Model;

internal class AppSyncParameters
{
    public string? GraphQLOperation { get; set; }
}

internal class AwsVpcConfiguration
{
    public List<string>? Subnets { get; set; } = [];
    public List<string>? SecurityGroups { get; set; } = [];
    public string? AssignPublicIp { get; set; }
}

internal class BatchArrayProperties
{
    public int? Size { get; set; }
}

internal class BatchParameters
{
    public string? JobDefinition { get; set; }
    public string? JobName { get; set; }
    public BatchArrayProperties? ArrayProperties { get; set; }
    public BatchRetryStrategy? RetryStrategy { get; set; }
}

internal class BatchRetryStrategy
{
    public int? Attempts { get; set; }
}

internal class CapacityProviderStrategyItem
{
    public string? CapacityProvider { get; set; }
    public int? Weight { get; set; }
    public int? Base { get; set; }
}

internal class CreateEventBusRequest
{
    public string? Name { get; set; }
    public string? EventSourceName { get; set; }
    public string? Description { get; set; }
    public string? KmsKeyIdentifier { get; set; }
    public DeadLetterConfig? DeadLetterConfig { get; set; }
    public LogConfig? LogConfig { get; set; }
    public List<Tag>? Tags { get; set; } = [];
}

internal class CreateEventBusResponse : AmazonWebServiceResponse
{
    public string? EventBusArn { get; set; }
    public string? Description { get; set; }
    public string? KmsKeyIdentifier { get; set; }
    public DeadLetterConfig? DeadLetterConfig { get; set; }
    public LogConfig? LogConfig { get; set; }
}

internal class DeadLetterConfig
{
    public string? Arn { get; set; }
}

internal class DeleteEventBusRequest
{
    public string? Name { get; set; }
}

internal class DeleteRuleRequest
{
    public string? Name { get; set; }
    public string? EventBusName { get; set; }
    public bool? Force { get; set; }
}

internal class DescribeEventBusRequest
{
    public string? Name { get; set; }
}

internal class DescribeEventBusResponse : AmazonWebServiceResponse
{
    public string? Name { get; set; }
    public string? Arn { get; set; }
    public string? Description { get; set; }
    public string? KmsKeyIdentifier { get; set; }
    public DeadLetterConfig? DeadLetterConfig { get; set; }
    public string? Policy { get; set; }
    public LogConfig? LogConfig { get; set; }
    public DateTime? CreationTime { get; set; }
    public DateTime? LastModifiedTime { get; set; }
}

internal class DescribeRuleRequest
{
    public string? Name { get; set; }
    public string? EventBusName { get; set; }
}

internal class DescribeRuleResponse : AmazonWebServiceResponse
{
    public string? Name { get; set; }
    public string? Arn { get; set; }
    public string? EventPattern { get; set; }
    public string? ScheduleExpression { get; set; }
    public string? State { get; set; }
    public string? Description { get; set; }
    public string? RoleArn { get; set; }
    public string? ManagedBy { get; set; }
    public string? EventBusName { get; set; }
    public string? CreatedBy { get; set; }
}

internal class DisableRuleRequest
{
    public string? Name { get; set; }
    public string? EventBusName { get; set; }
}

internal class EcsParameters
{
    public string? TaskDefinitionArn { get; set; }
    public int? TaskCount { get; set; }
    public string? LaunchType { get; set; }
    public NetworkConfiguration? NetworkConfiguration { get; set; }
    public string? PlatformVersion { get; set; }
    public string? Group { get; set; }
    public List<CapacityProviderStrategyItem>? CapacityProviderStrategy { get; set; } = [];
    public bool? EnableECSManagedTags { get; set; }
    public bool? EnableExecuteCommand { get; set; }
    public List<PlacementConstraint>? PlacementConstraints { get; set; } = [];
    public List<PlacementStrategy>? PlacementStrategy { get; set; } = [];
    public string? PropagateTags { get; set; }
    public string? ReferenceId { get; set; }
    public List<Tag>? Tags { get; set; } = [];
}

internal class EnableRuleRequest
{
    public string? Name { get; set; }
    public string? EventBusName { get; set; }
}

internal class EventBus
{
    public string? Name { get; set; }
    public string? Arn { get; set; }
    public string? Description { get; set; }
    public string? Policy { get; set; }
    public DateTime? CreationTime { get; set; }
    public DateTime? LastModifiedTime { get; set; }
}

internal class HttpParameters
{
    public List<string>? PathParameterValues { get; set; } = [];
    public Dictionary<string, string>? HeaderParameters { get; set; } = [];
    public Dictionary<string, string>? QueryStringParameters { get; set; } = [];
}

internal class InputTransformer
{
    public Dictionary<string, string>? InputPathsMap { get; set; } = [];
    public string? InputTemplate { get; set; }
}

internal class KinesisParameters
{
    public string? PartitionKeyPath { get; set; }
}

internal class ListEventBusesRequest
{
    public string? NamePrefix { get; set; }
    public string? NextToken { get; set; }
    public int? Limit { get; set; }
}

internal class ListEventBusesResponse : AmazonWebServiceResponse
{
    public List<EventBus>? EventBuses { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListRuleNamesByTargetRequest
{
    public string? TargetArn { get; set; }
    public string? EventBusName { get; set; }
    public string? NextToken { get; set; }
    public int? Limit { get; set; }
}

internal class ListRuleNamesByTargetResponse : AmazonWebServiceResponse
{
    public List<string>? RuleNames { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListRulesRequest
{
    public string? NamePrefix { get; set; }
    public string? EventBusName { get; set; }
    public string? NextToken { get; set; }
    public int? Limit { get; set; }
}

internal class ListRulesResponse : AmazonWebServiceResponse
{
    public List<Rule>? Rules { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListTargetsByRuleRequest
{
    public string? Rule { get; set; }
    public string? EventBusName { get; set; }
    public string? NextToken { get; set; }
    public int? Limit { get; set; }
}

internal class ListTargetsByRuleResponse : AmazonWebServiceResponse
{
    public List<Target>? Targets { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class LogConfig
{
    public string? IncludeDetail { get; set; }
    public string? Level { get; set; }
}

internal class NetworkConfiguration
{
    public AwsVpcConfiguration? AwsvpcConfiguration { get; set; }
}

internal class PlacementConstraint
{
    public string? Type { get; set; }
    public string? Expression { get; set; }
}

internal class PlacementStrategy
{
    public string? Type { get; set; }
    public string? Field { get; set; }
}

internal class PutEventsRequest
{
    public List<PutEventsRequestEntry>? Entries { get; set; } = [];
    public string? EndpointId { get; set; }
}

internal class PutEventsRequestEntry
{
    public DateTime? Time { get; set; }
    public string? Source { get; set; }
    public List<string>? Resources { get; set; } = [];
    public string? DetailType { get; set; }
    public string? Detail { get; set; }
    public string? EventBusName { get; set; }
    public string? TraceHeader { get; set; }
}

internal class PutEventsResponse : AmazonWebServiceResponse
{
    public int? FailedEntryCount { get; set; }
    public List<PutEventsResultEntry>? Entries { get; set; } = [];
}

internal class PutEventsResultEntry
{
    public string? EventId { get; set; }
    public string? ErrorCode { get; set; }
    public string? ErrorMessage { get; set; }
}

internal class PutRuleRequest
{
    public string? Name { get; set; }
    public string? ScheduleExpression { get; set; }
    public string? EventPattern { get; set; }
    public string? State { get; set; }
    public string? Description { get; set; }
    public string? RoleArn { get; set; }
    public List<Tag>? Tags { get; set; } = [];
    public string? EventBusName { get; set; }
}

internal class PutRuleResponse : AmazonWebServiceResponse
{
    public string? RuleArn { get; set; }
}

internal class PutTargetsRequest
{
    public string? Rule { get; set; }
    public string? EventBusName { get; set; }
    public List<Target>? Targets { get; set; } = [];
}

internal class PutTargetsResponse : AmazonWebServiceResponse
{
    public int? FailedEntryCount { get; set; }
    public List<PutTargetsResultEntry>? FailedEntries { get; set; } = [];
}

internal class PutTargetsResultEntry
{
    public string? TargetId { get; set; }
    public string? ErrorCode { get; set; }
    public string? ErrorMessage { get; set; }
}

internal class RedshiftDataParameters
{
    public string? SecretManagerArn { get; set; }
    public string? Database { get; set; }
    public string? DbUser { get; set; }
    public string? Sql { get; set; }
    public string? StatementName { get; set; }
    public bool? WithEvent { get; set; }
    public List<string>? Sqls { get; set; } = [];
}

internal class RemoveTargetsRequest
{
    public string? Rule { get; set; }
    public string? EventBusName { get; set; }
    public List<string>? Ids { get; set; } = [];
    public bool? Force { get; set; }
}

internal class RemoveTargetsResponse : AmazonWebServiceResponse
{
    public int? FailedEntryCount { get; set; }
    public List<RemoveTargetsResultEntry>? FailedEntries { get; set; } = [];
}

internal class RemoveTargetsResultEntry
{
    public string? TargetId { get; set; }
    public string? ErrorCode { get; set; }
    public string? ErrorMessage { get; set; }
}

internal class RetryPolicy
{
    public int? MaximumRetryAttempts { get; set; }
    public int? MaximumEventAgeInSeconds { get; set; }
}

internal class Rule
{
    public string? Name { get; set; }
    public string? Arn { get; set; }
    public string? EventPattern { get; set; }
    public string? State { get; set; }
    public string? Description { get; set; }
    public string? ScheduleExpression { get; set; }
    public string? RoleArn { get; set; }
    public string? ManagedBy { get; set; }
    public string? EventBusName { get; set; }
}

internal class RunCommandParameters
{
    public List<RunCommandTarget>? RunCommandTargets { get; set; } = [];
}

internal class RunCommandTarget
{
    public string? Key { get; set; }
    public List<string>? Values { get; set; } = [];
}

internal class SageMakerPipelineParameter
{
    public string? Name { get; set; }
    public string? Value { get; set; }
}

internal class SageMakerPipelineParameters
{
    public List<SageMakerPipelineParameter>? PipelineParameterList { get; set; } = [];
}

internal class SqsParameters
{
    public string? MessageGroupId { get; set; }
}

internal class Tag
{
    public string? Key { get; set; }
    public string? Value { get; set; }
}

internal class Target
{
    public string? Id { get; set; }
    public string? Arn { get; set; }
    public string? RoleArn { get; set; }
    public string? Input { get; set; }
    public string? InputPath { get; set; }
    public InputTransformer? InputTransformer { get; set; }
    public KinesisParameters? KinesisParameters { get; set; }
    public RunCommandParameters? RunCommandParameters { get; set; }
    public EcsParameters? EcsParameters { get; set; }
    public BatchParameters? BatchParameters { get; set; }
    public SqsParameters? SqsParameters { get; set; }
    public HttpParameters? HttpParameters { get; set; }
    public RedshiftDataParameters? RedshiftDataParameters { get; set; }
    public SageMakerPipelineParameters? SageMakerPipelineParameters { get; set; }
    public DeadLetterConfig? DeadLetterConfig { get; set; }
    public RetryPolicy? RetryPolicy { get; set; }
    public AppSyncParameters? AppSyncParameters { get; set; }
}

internal class TestEventPatternRequest
{
    public string? EventPattern { get; set; }
    public string? Event { get; set; }
}

internal class TestEventPatternResponse : AmazonWebServiceResponse
{
    public bool? Result { get; set; }
}

internal class DeleteEventBusResponse : AmazonWebServiceResponse { }

internal class DeleteRuleResponse : AmazonWebServiceResponse { }

internal class DisableRuleResponse : AmazonWebServiceResponse { }

internal class EnableRuleResponse : AmazonWebServiceResponse { }

