// <auto-generated/>
// Generated internal POCO types for Sns from AWS service model
#nullable enable

namespace LocalSqsSnsMessaging.Sns.Model;

internal class AddPermissionRequest
{
    public string? TopicArn { get; set; }
    public string? Label { get; set; }
    public List<string>? AWSAccountId { get; set; } = [];
    public List<string>? ActionName { get; set; } = [];
}

internal class BatchResultErrorEntry
{
    public string? Id { get; set; }
    public string? Code { get; set; }
    public string? Message { get; set; }
    public bool? SenderFault { get; set; }
}

internal class CheckIfPhoneNumberIsOptedOutRequest
{
    public string? PhoneNumber { get; set; }
}

internal class CheckIfPhoneNumberIsOptedOutResponse : AmazonWebServiceResponse
{
    public bool? IsOptedOut { get; set; }
}

internal class ConfirmSubscriptionRequest
{
    public string? TopicArn { get; set; }
    public string? Token { get; set; }
    public string? AuthenticateOnUnsubscribe { get; set; }
}

internal class ConfirmSubscriptionResponse : AmazonWebServiceResponse
{
    public string? SubscriptionArn { get; set; }
}

internal class CreatePlatformApplicationRequest
{
    public string? Name { get; set; }
    public string? Platform { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class CreatePlatformApplicationResponse : AmazonWebServiceResponse
{
    public string? PlatformApplicationArn { get; set; }
}

internal class CreatePlatformEndpointRequest
{
    public string? PlatformApplicationArn { get; set; }
    public string? Token { get; set; }
    public string? CustomUserData { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class CreatePlatformEndpointResponse : AmazonWebServiceResponse
{
    public string? EndpointArn { get; set; }
}

internal class CreateSMSSandboxPhoneNumberRequest
{
    public string? PhoneNumber { get; set; }
    public string? LanguageCode { get; set; }
}

internal class CreateSMSSandboxPhoneNumberResponse : AmazonWebServiceResponse
{
}

internal class CreateTopicRequest
{
    public string? Name { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
    public List<Tag>? Tags { get; set; } = [];
    public string? DataProtectionPolicy { get; set; }
}

internal class CreateTopicResponse : AmazonWebServiceResponse
{
    public string? TopicArn { get; set; }
}

internal class DeleteEndpointRequest
{
    public string? EndpointArn { get; set; }
}

internal class DeletePlatformApplicationRequest
{
    public string? PlatformApplicationArn { get; set; }
}

internal class DeleteSMSSandboxPhoneNumberRequest
{
    public string? PhoneNumber { get; set; }
}

internal class DeleteSMSSandboxPhoneNumberResponse : AmazonWebServiceResponse
{
}

internal class DeleteTopicRequest
{
    public string? TopicArn { get; set; }
}

internal class Endpoint
{
    public string? EndpointArn { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class GetDataProtectionPolicyRequest
{
    public string? ResourceArn { get; set; }
}

internal class GetDataProtectionPolicyResponse : AmazonWebServiceResponse
{
    public string? DataProtectionPolicy { get; set; }
}

internal class GetEndpointAttributesRequest
{
    public string? EndpointArn { get; set; }
}

internal class GetEndpointAttributesResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class GetPlatformApplicationAttributesRequest
{
    public string? PlatformApplicationArn { get; set; }
}

internal class GetPlatformApplicationAttributesResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class GetSMSAttributesRequest
{
    public List<string>? Attributes { get; set; } = [];
}

internal class GetSMSAttributesResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class GetSMSSandboxAccountStatusRequest
{
}

internal class GetSMSSandboxAccountStatusResponse : AmazonWebServiceResponse
{
    public bool? IsInSandbox { get; set; }
}

internal class GetSubscriptionAttributesRequest
{
    public string? SubscriptionArn { get; set; }
}

internal class GetSubscriptionAttributesResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class GetTopicAttributesRequest
{
    public string? TopicArn { get; set; }
}

internal class GetTopicAttributesResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class ListEndpointsByPlatformApplicationRequest
{
    public string? PlatformApplicationArn { get; set; }
    public string? NextToken { get; set; }
}

internal class ListEndpointsByPlatformApplicationResponse : AmazonWebServiceResponse
{
    public List<Endpoint>? Endpoints { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListOriginationNumbersRequest
{
    public string? NextToken { get; set; }
    public int? MaxResults { get; set; }
}

internal class ListOriginationNumbersResponse : AmazonWebServiceResponse
{
    public string? NextToken { get; set; }
    public List<PhoneNumberInformation>? PhoneNumbers { get; set; } = [];
}

internal class ListPhoneNumbersOptedOutRequest
{
    public string? NextToken { get; set; }
}

internal class ListPhoneNumbersOptedOutResponse : AmazonWebServiceResponse
{
    public List<string>? PhoneNumbers { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListPlatformApplicationsRequest
{
    public string? NextToken { get; set; }
}

internal class ListPlatformApplicationsResponse : AmazonWebServiceResponse
{
    public List<PlatformApplication>? PlatformApplications { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListSMSSandboxPhoneNumbersRequest
{
    public string? NextToken { get; set; }
    public int? MaxResults { get; set; }
}

internal class ListSMSSandboxPhoneNumbersResponse : AmazonWebServiceResponse
{
    public List<SMSSandboxPhoneNumber>? PhoneNumbers { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListSubscriptionsByTopicRequest
{
    public string? TopicArn { get; set; }
    public string? NextToken { get; set; }
}

internal class ListSubscriptionsByTopicResponse : AmazonWebServiceResponse
{
    public List<Subscription>? Subscriptions { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListSubscriptionsRequest
{
    public string? NextToken { get; set; }
}

internal class ListSubscriptionsResponse : AmazonWebServiceResponse
{
    public List<Subscription>? Subscriptions { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListTagsForResourceRequest
{
    public string? ResourceArn { get; set; }
}

internal class ListTagsForResourceResponse : AmazonWebServiceResponse
{
    public List<Tag>? Tags { get; set; } = [];
}

internal class ListTopicsRequest
{
    public string? NextToken { get; set; }
}

internal class ListTopicsResponse : AmazonWebServiceResponse
{
    public List<Topic>? Topics { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class MessageAttributeValue
{
    public string? DataType { get; set; }
    public string? StringValue { get; set; }
    public MemoryStream? BinaryValue { get; set; }
}

internal class OptInPhoneNumberRequest
{
    public string? PhoneNumber { get; set; }
}

internal class OptInPhoneNumberResponse : AmazonWebServiceResponse
{
}

internal class PhoneNumberInformation
{
    public DateTime? CreatedAt { get; set; }
    public string? PhoneNumber { get; set; }
    public string? Status { get; set; }
    public string? Iso2CountryCode { get; set; }
    public string? RouteType { get; set; }
    public List<string>? NumberCapabilities { get; set; } = [];
}

internal class PlatformApplication
{
    public string? PlatformApplicationArn { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class PublishBatchRequest
{
    public string? TopicArn { get; set; }
    public List<PublishBatchRequestEntry>? PublishBatchRequestEntries { get; set; } = [];
}

internal class PublishBatchRequestEntry
{
    public string? Id { get; set; }
    public string? Message { get; set; }
    public string? Subject { get; set; }
    public string? MessageStructure { get; set; }
    public Dictionary<string, MessageAttributeValue>? MessageAttributes { get; set; } = [];
    public string? MessageDeduplicationId { get; set; }
    public string? MessageGroupId { get; set; }
}

internal class PublishBatchResponse : AmazonWebServiceResponse
{
    public List<PublishBatchResultEntry>? Successful { get; set; } = [];
    public List<BatchResultErrorEntry>? Failed { get; set; } = [];
}

internal class PublishBatchResultEntry
{
    public string? Id { get; set; }
    public string? MessageId { get; set; }
    public string? SequenceNumber { get; set; }
}

internal class PublishRequest
{
    public string? TopicArn { get; set; }
    public string? TargetArn { get; set; }
    public string? PhoneNumber { get; set; }
    public string? Message { get; set; }
    public string? Subject { get; set; }
    public string? MessageStructure { get; set; }
    public Dictionary<string, MessageAttributeValue>? MessageAttributes { get; set; } = [];
    public string? MessageDeduplicationId { get; set; }
    public string? MessageGroupId { get; set; }
}

internal class PublishResponse : AmazonWebServiceResponse
{
    public string? MessageId { get; set; }
    public string? SequenceNumber { get; set; }
}

internal class PutDataProtectionPolicyRequest
{
    public string? ResourceArn { get; set; }
    public string? DataProtectionPolicy { get; set; }
}

internal class RemovePermissionRequest
{
    public string? TopicArn { get; set; }
    public string? Label { get; set; }
}

internal class SetEndpointAttributesRequest
{
    public string? EndpointArn { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class SetPlatformApplicationAttributesRequest
{
    public string? PlatformApplicationArn { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class SetSMSAttributesRequest
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class SetSMSAttributesResponse : AmazonWebServiceResponse
{
}

internal class SetSubscriptionAttributesRequest
{
    public string? SubscriptionArn { get; set; }
    public string? AttributeName { get; set; }
    public string? AttributeValue { get; set; }
}

internal class SetTopicAttributesRequest
{
    public string? TopicArn { get; set; }
    public string? AttributeName { get; set; }
    public string? AttributeValue { get; set; }
}

internal class SMSSandboxPhoneNumber
{
    public string? PhoneNumber { get; set; }
    public string? Status { get; set; }
}

internal class SubscribeRequest
{
    public string? TopicArn { get; set; }
    public string? Protocol { get; set; }
    public string? Endpoint { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
    public bool? ReturnSubscriptionArn { get; set; }
}

internal class SubscribeResponse : AmazonWebServiceResponse
{
    public string? SubscriptionArn { get; set; }
}

internal class Subscription
{
    public string? SubscriptionArn { get; set; }
    public string? Owner { get; set; }
    public string? Protocol { get; set; }
    public string? Endpoint { get; set; }
    public string? TopicArn { get; set; }
}

internal class Tag
{
    public string? Key { get; set; }
    public string? Value { get; set; }
}

internal class TagResourceRequest
{
    public string? ResourceArn { get; set; }
    public List<Tag>? Tags { get; set; } = [];
}

internal class TagResourceResponse : AmazonWebServiceResponse
{
}

internal class Topic
{
    public string? TopicArn { get; set; }
}

internal class UnsubscribeRequest
{
    public string? SubscriptionArn { get; set; }
}

internal class UntagResourceRequest
{
    public string? ResourceArn { get; set; }
    public List<string>? TagKeys { get; set; } = [];
}

internal class UntagResourceResponse : AmazonWebServiceResponse
{
}

internal class VerifySMSSandboxPhoneNumberRequest
{
    public string? PhoneNumber { get; set; }
    public string? OneTimePassword { get; set; }
}

internal class VerifySMSSandboxPhoneNumberResponse : AmazonWebServiceResponse
{
}

internal class AddPermissionResponse : AmazonWebServiceResponse { }

internal class DeleteEndpointResponse : AmazonWebServiceResponse { }

internal class DeletePlatformApplicationResponse : AmazonWebServiceResponse { }

internal class DeleteTopicResponse : AmazonWebServiceResponse { }

internal class PutDataProtectionPolicyResponse : AmazonWebServiceResponse { }

internal class RemovePermissionResponse : AmazonWebServiceResponse { }

internal class SetEndpointAttributesResponse : AmazonWebServiceResponse { }

internal class SetPlatformApplicationAttributesResponse : AmazonWebServiceResponse { }

internal class SetSubscriptionAttributesResponse : AmazonWebServiceResponse { }

internal class SetTopicAttributesResponse : AmazonWebServiceResponse { }

internal class UnsubscribeResponse : AmazonWebServiceResponse { }

