// <auto-generated/>
// Generated internal POCO types for Sqs from AWS service model
#nullable enable

namespace LocalSqsSnsMessaging.Sqs.Model;

internal class AddPermissionRequest
{
    public string? QueueUrl { get; set; }
    public string? Label { get; set; }
    public List<string>? AWSAccountIds { get; set; } = [];
    public List<string>? Actions { get; set; } = [];
}

internal class BatchResultErrorEntry
{
    public string? Id { get; set; }
    public bool? SenderFault { get; set; }
    public string? Code { get; set; }
    public string? Message { get; set; }
}

internal class CancelMessageMoveTaskRequest
{
    public string? TaskHandle { get; set; }
}

internal class CancelMessageMoveTaskResponse : AmazonWebServiceResponse
{
    public long? ApproximateNumberOfMessagesMoved { get; set; }
}

internal class ChangeMessageVisibilityBatchRequest
{
    public string? QueueUrl { get; set; }
    public List<ChangeMessageVisibilityBatchRequestEntry>? Entries { get; set; } = [];
}

internal class ChangeMessageVisibilityBatchRequestEntry
{
    public string? Id { get; set; }
    public string? ReceiptHandle { get; set; }
    public int? VisibilityTimeout { get; set; }
}

internal class ChangeMessageVisibilityBatchResponse : AmazonWebServiceResponse
{
    public List<ChangeMessageVisibilityBatchResultEntry>? Successful { get; set; } = [];
    public List<BatchResultErrorEntry>? Failed { get; set; } = [];
}

internal class ChangeMessageVisibilityBatchResultEntry
{
    public string? Id { get; set; }
}

internal class ChangeMessageVisibilityRequest
{
    public string? QueueUrl { get; set; }
    public string? ReceiptHandle { get; set; }
    public int? VisibilityTimeout { get; set; }
}

internal class CreateQueueRequest
{
    public string? QueueName { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
    public Dictionary<string, string>? Tags { get; set; } = [];
}

internal class CreateQueueResponse : AmazonWebServiceResponse
{
    public string? QueueUrl { get; set; }
}

internal class DeleteMessageBatchRequest
{
    public string? QueueUrl { get; set; }
    public List<DeleteMessageBatchRequestEntry>? Entries { get; set; } = [];
}

internal class DeleteMessageBatchRequestEntry
{
    public string? Id { get; set; }
    public string? ReceiptHandle { get; set; }
}

internal class DeleteMessageBatchResponse : AmazonWebServiceResponse
{
    public List<DeleteMessageBatchResultEntry>? Successful { get; set; } = [];
    public List<BatchResultErrorEntry>? Failed { get; set; } = [];
}

internal class DeleteMessageBatchResultEntry
{
    public string? Id { get; set; }
}

internal class DeleteMessageRequest
{
    public string? QueueUrl { get; set; }
    public string? ReceiptHandle { get; set; }
}

internal class DeleteQueueRequest
{
    public string? QueueUrl { get; set; }
}

internal class GetQueueAttributesRequest
{
    public string? QueueUrl { get; set; }
    public List<string>? AttributeNames { get; set; } = [];
}

internal class GetQueueAttributesResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class GetQueueUrlRequest
{
    public string? QueueName { get; set; }
    public string? QueueOwnerAWSAccountId { get; set; }
}

internal class GetQueueUrlResponse : AmazonWebServiceResponse
{
    public string? QueueUrl { get; set; }
}

internal class ListDeadLetterSourceQueuesRequest
{
    public string? QueueUrl { get; set; }
    public string? NextToken { get; set; }
    public int? MaxResults { get; set; }
}

internal class ListDeadLetterSourceQueuesResponse : AmazonWebServiceResponse
{
    public List<string>? QueueUrls { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListMessageMoveTasksRequest
{
    public string? SourceArn { get; set; }
    public int? MaxResults { get; set; }
}

internal class ListMessageMoveTasksResponse : AmazonWebServiceResponse
{
    public List<ListMessageMoveTasksResultEntry>? Results { get; set; } = [];
}

internal class ListMessageMoveTasksResultEntry
{
    public string? TaskHandle { get; set; }
    public string? Status { get; set; }
    public string? SourceArn { get; set; }
    public string? DestinationArn { get; set; }
    public int? MaxNumberOfMessagesPerSecond { get; set; }
    public long? ApproximateNumberOfMessagesMoved { get; set; }
    public long? ApproximateNumberOfMessagesToMove { get; set; }
    public string? FailureReason { get; set; }
    public long? StartedTimestamp { get; set; }
}

internal class ListQueuesRequest
{
    public string? QueueNamePrefix { get; set; }
    public string? NextToken { get; set; }
    public int? MaxResults { get; set; }
}

internal class ListQueuesResponse : AmazonWebServiceResponse
{
    public List<string>? QueueUrls { get; set; } = [];
    public string? NextToken { get; set; }
}

internal class ListQueueTagsRequest
{
    public string? QueueUrl { get; set; }
}

internal class ListQueueTagsResponse : AmazonWebServiceResponse
{
    public Dictionary<string, string>? Tags { get; set; } = [];
}

internal class Message
{
    public string? MessageId { get; set; }
    public string? ReceiptHandle { get; set; }
    public string? MD5OfBody { get; set; }
    public string? Body { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
    public string? MD5OfMessageAttributes { get; set; }
    public Dictionary<string, MessageAttributeValue>? MessageAttributes { get; set; } = [];
}

internal class MessageAttributeValue
{
    public string? StringValue { get; set; }
    public MemoryStream? BinaryValue { get; set; }
    public List<string>? StringListValues { get; set; } = [];
    public List<MemoryStream>? BinaryListValues { get; set; } = [];
    public string? DataType { get; set; }
}

internal class MessageSystemAttributeValue
{
    public string? StringValue { get; set; }
    public MemoryStream? BinaryValue { get; set; }
    public List<string>? StringListValues { get; set; } = [];
    public List<MemoryStream>? BinaryListValues { get; set; } = [];
    public string? DataType { get; set; }
}

internal class PurgeQueueRequest
{
    public string? QueueUrl { get; set; }
}

internal class ReceiveMessageRequest
{
    public string? QueueUrl { get; set; }
    public List<string>? AttributeNames { get; set; } = [];
    public List<string>? MessageSystemAttributeNames { get; set; } = [];
    public List<string>? MessageAttributeNames { get; set; } = [];
    public int? MaxNumberOfMessages { get; set; }
    public int? VisibilityTimeout { get; set; }
    public int? WaitTimeSeconds { get; set; }
    public string? ReceiveRequestAttemptId { get; set; }
}

internal class ReceiveMessageResponse : AmazonWebServiceResponse
{
    public List<Message>? Messages { get; set; } = [];
}

internal class RemovePermissionRequest
{
    public string? QueueUrl { get; set; }
    public string? Label { get; set; }
}

internal class SendMessageBatchRequest
{
    public string? QueueUrl { get; set; }
    public List<SendMessageBatchRequestEntry>? Entries { get; set; } = [];
}

internal class SendMessageBatchRequestEntry
{
    public string? Id { get; set; }
    public string? MessageBody { get; set; }
    public int? DelaySeconds { get; set; }
    public Dictionary<string, MessageAttributeValue>? MessageAttributes { get; set; } = [];
    public Dictionary<string, MessageSystemAttributeValue>? MessageSystemAttributes { get; set; } = [];
    public string? MessageDeduplicationId { get; set; }
    public string? MessageGroupId { get; set; }
}

internal class SendMessageBatchResponse : AmazonWebServiceResponse
{
    public List<SendMessageBatchResultEntry>? Successful { get; set; } = [];
    public List<BatchResultErrorEntry>? Failed { get; set; } = [];
}

internal class SendMessageBatchResultEntry
{
    public string? Id { get; set; }
    public string? MessageId { get; set; }
    public string? MD5OfMessageBody { get; set; }
    public string? MD5OfMessageAttributes { get; set; }
    public string? MD5OfMessageSystemAttributes { get; set; }
    public string? SequenceNumber { get; set; }
}

internal class SendMessageRequest
{
    public string? QueueUrl { get; set; }
    public string? MessageBody { get; set; }
    public int? DelaySeconds { get; set; }
    public Dictionary<string, MessageAttributeValue>? MessageAttributes { get; set; } = [];
    public Dictionary<string, MessageSystemAttributeValue>? MessageSystemAttributes { get; set; } = [];
    public string? MessageDeduplicationId { get; set; }
    public string? MessageGroupId { get; set; }
}

internal class SendMessageResponse : AmazonWebServiceResponse
{
    public string? MD5OfMessageBody { get; set; }
    public string? MD5OfMessageAttributes { get; set; }
    public string? MD5OfMessageSystemAttributes { get; set; }
    public string? MessageId { get; set; }
    public string? SequenceNumber { get; set; }
}

internal class SetQueueAttributesRequest
{
    public string? QueueUrl { get; set; }
    public Dictionary<string, string>? Attributes { get; set; } = [];
}

internal class StartMessageMoveTaskRequest
{
    public string? SourceArn { get; set; }
    public string? DestinationArn { get; set; }
    public int? MaxNumberOfMessagesPerSecond { get; set; }
}

internal class StartMessageMoveTaskResponse : AmazonWebServiceResponse
{
    public string? TaskHandle { get; set; }
}

internal class TagQueueRequest
{
    public string? QueueUrl { get; set; }
    public Dictionary<string, string>? Tags { get; set; } = [];
}

internal class UntagQueueRequest
{
    public string? QueueUrl { get; set; }
    public List<string>? TagKeys { get; set; } = [];
}

internal class AddPermissionResponse : AmazonWebServiceResponse { }

internal class ChangeMessageVisibilityResponse : AmazonWebServiceResponse { }

internal class DeleteMessageResponse : AmazonWebServiceResponse { }

internal class DeleteQueueResponse : AmazonWebServiceResponse { }

internal class PurgeQueueResponse : AmazonWebServiceResponse { }

internal class RemovePermissionResponse : AmazonWebServiceResponse { }

internal class SetQueueAttributesResponse : AmazonWebServiceResponse { }

internal class TagQueueResponse : AmazonWebServiceResponse { }

internal class UntagQueueResponse : AmazonWebServiceResponse { }

